[package]
name = "agglayer-telemetry"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
axum = "=0.7.7"
buildstructor.workspace = true
futures.workspace = true
lazy_static.workspace = true
opentelemetry = { version = "0.24.0", features = ["metrics"] }
opentelemetry-prometheus = "0.17.0"
opentelemetry_sdk = { version = "0.24.1", features = ["metrics"] }
prometheus = "0.13.3"
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true }
tracing.workspace = true
