[package]
name = "agglayer-contracts"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
alloy-primitives.workspace = true
async-trait.workspace = true
ethers.workspace = true
ethers-contract = "2.0.14"

[build-dependencies]
ethers-contract = "2.0.14"
